name: Deploy Bicep Template at Subscription Scope

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep to subscription scope
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        template: ./main.bicep
        parameters: >
          storageAccountName=mystorageacct1234
          resourceGroupName=my-bicep-rg
        location: swedencentral
        deploymentName: bicep-deploy
